version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: Korn
      POSTGRES_USER: postgres1
      POSTGRES_PASSWORD: postgres123
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db